# Generated by Django 3.0.2 on 2020-01-30 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Truck', models.CharField(max_length=50)),
                ('TBC', models.CharField(max_length=50)),
                ('H180J', models.CharField(max_length=10)),
                ('FC505', models.CharField(max_length=10)),
                ('FC503', models.CharField(max_length=10)),
                ('FC504', models.CharField(max_length=10)),
                ('M441R', models.CharField(max_length=10)),
                ('Q738U', models.CharField(max_length=10)),
                ('BC606', models.CharField(max_length=10)),
                ('BC606B', models.CharField(max_length=10)),
                ('BC604', models.CharField(max_length=10)),
                ('BC604B', models.CharField(max_length=10)),
                ('BC605', models.CharField(max_length=10)),
                ('BC605B', models.CharField(max_length=10)),
                ('BC607', models.CharField(max_length=10)),
                ('BC607B', models.CharField(max_length=10)),
                ('BC608', models.CharField(max_length=10)),
                ('BC608B', models.CharField(max_length=10)),
                ('BC602', models.CharField(max_length=10)),
                ('BC602B', models.CharField(max_length=10)),
                ('BC619', models.CharField(max_length=10)),
                ('BC619B', models.CharField(max_length=10)),
                ('BC603', models.CharField(max_length=10)),
                ('BC603B', models.CharField(max_length=10)),
                ('BC615', models.CharField(max_length=10)),
                ('BC615B', models.CharField(max_length=10)),
                ('BC620', models.CharField(max_length=10)),
                ('BC620B', models.CharField(max_length=10)),
                ('BC609', models.CharField(max_length=10)),
                ('BC609B', models.CharField(max_length=10)),
                ('FC502', models.CharField(max_length=10)),
                ('FC501', models.CharField(max_length=10)),
                ('BC614', models.CharField(max_length=10)),
                ('BC614B', models.CharField(max_length=10)),
                ('BC621', models.CharField(max_length=10)),
                ('BC621B', models.CharField(max_length=10)),
                ('BC610', models.CharField(max_length=10)),
                ('BC610B', models.CharField(max_length=10)),
                ('BC622', models.CharField(max_length=10)),
                ('BC622B', models.CharField(max_length=10)),
                ('BC623', models.CharField(max_length=10)),
                ('BC623B', models.CharField(max_length=10)),
                ('Spare1', models.CharField(max_length=10)),
                ('Spare2', models.CharField(max_length=10)),
                ('Spare3', models.CharField(max_length=10)),
                ('Spare4', models.CharField(max_length=10)),
                ('Spare5', models.CharField(max_length=10)),
                ('Spare6', models.CharField(max_length=10)),
                ('Spare7', models.CharField(max_length=10)),
                ('Spare8', models.CharField(max_length=10)),
                ('Spare9', models.CharField(max_length=10)),
                ('Spare10', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staffname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(choices=[('FCC', 'FCC'), ('CHC1', 'CHC1'), ('CHC2', 'CHC2'), ('CHC3', 'CHC3'), ('CHC4', 'CHC4'), ('CHC5', 'CHC5'), ('CHC6', 'CHC6'), ('CCI', 'CCI'), ('CHIG', 'CHIG'), ('FCI', 'FCI'), ('CHI', 'CHI'), ('CHI2', 'CHI2'), ('FCD', 'FCD'), ('CHD1', 'CHD1'), ('CHD2', 'CHD2'), ('CHD3', 'CHD3'), ('CHD4', 'CHD4'), ('CHD5', 'CHD5'), ('CHD6', 'CHD6'), ('CBN', 'CBN'), ('CBN1', 'CBN1'), ('CHN', 'CHN'), ('CHN1', 'CHN1'), ('CHN2', 'CHN2'), ('FCT', 'FCT'), ('CHT1', 'CHT1'), ('CHT2', 'CHT2'), ('CHW', 'CHW'), ('CHW1', 'CHW1')], max_length=10)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('truck', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_1', models.CharField(choices=[('H180J', 'H180J'), ('FC505', 'FC505'), ('FC503', 'FC503'), ('FC504', 'FC504'), ('M441R', 'M441R'), ('Q738U', 'Q738U'), ('BC606', 'BC606'), ('BC604', 'BC604'), ('BC605', 'BC605'), ('BC607', 'BC607'), ('BC608', 'BC608'), ('BC602', 'BC602'), ('BC619', 'BC619'), ('BC603', 'BC603'), ('BC615', 'BC615'), ('BC620', 'BC620'), ('BC609', 'BC609'), ('FC502', 'FC502'), ('BC614', 'BC614'), ('BC621', 'BC621'), ('BC610', 'BC610'), ('BC622', 'BC622'), ('BC623', 'BC623'), ('TO BE CONFIRMED', 'TO BE CONFIRMED')], max_length=50)),
                ('trailer_2', models.CharField(blank=True, choices=[('BC606B', 'BC606B'), ('BC604B', 'BC604B'), ('BC605B', 'BC605B'), ('BC607B', 'BC607B'), ('BC608B', 'BC608B'), ('BC602B', 'BC602B'), ('BC619B', 'BC619B'), ('BC603B', 'BC603B'), ('BC615B', 'BC615B'), ('BC620B', 'BC620B'), ('BC609B', 'BC609B'), ('FC501', 'FC501'), ('BC614B', 'BC614B'), ('BC621B', 'BC621B'), ('BC610B', 'BC610B'), ('5Y411', '5Y411'), ('BC622B', 'BC622B'), ('BC623B', 'BC623B')], max_length=50, null=True)),
                ('load_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('return_load_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('Planned_depart_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
