# Generated by Django 3.0.2 on 2020-01-23 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('driver', models.CharField(max_length=50)),
                ('truck', models.CharField(max_length=50)),
                ('trailer_1', models.CharField(max_length=50)),
                ('trailer_2', models.CharField(max_length=50)),
                ('load_comments', models.CharField(max_length=255)),
                ('return_load_comments', models.CharField(max_length=255)),
                ('depart_date', models.DateField()),
                ('depart_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
