# Generated by Django 3.0.2 on 2020-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Truck', models.CharField(max_length=10)),
                ('H180J', models.CharField(max_length=10)),
                ('FC505', models.CharField(max_length=10)),
                ('FC503', models.CharField(max_length=10)),
                ('FC504', models.CharField(max_length=10)),
                ('M441R', models.CharField(max_length=10)),
                ('Q738U', models.CharField(max_length=10)),
                ('BC606', models.CharField(max_length=10)),
                ('BC606B', models.CharField(max_length=10)),
                ('BC604', models.CharField(max_length=10)),
                ('BC604B', models.CharField(max_length=10)),
                ('BC605', models.CharField(max_length=10)),
                ('BC605B', models.CharField(max_length=10)),
                ('BC607', models.CharField(max_length=10)),
                ('BC607B', models.CharField(max_length=10)),
                ('BC608', models.CharField(max_length=10)),
                ('BC608B', models.CharField(max_length=10)),
                ('BC602', models.CharField(max_length=10)),
                ('BC602B', models.CharField(max_length=10)),
                ('BC619', models.CharField(max_length=10)),
                ('BC619B', models.CharField(max_length=10)),
                ('BC603', models.CharField(max_length=10)),
                ('BC603B', models.CharField(max_length=10)),
                ('BC615', models.CharField(max_length=10)),
                ('BC615B', models.CharField(max_length=10)),
                ('BC620', models.CharField(max_length=10)),
                ('BC620B', models.CharField(max_length=10)),
                ('BC609', models.CharField(max_length=10)),
                ('BC609B', models.CharField(max_length=10)),
                ('FC502', models.CharField(max_length=10)),
                ('FC501', models.CharField(max_length=10)),
                ('BC614', models.CharField(max_length=10)),
                ('BC614B', models.CharField(max_length=10)),
                ('BC621', models.CharField(max_length=10)),
                ('BC621B', models.CharField(max_length=10)),
                ('BC610', models.CharField(max_length=10)),
                ('BC610B', models.CharField(max_length=10)),
                ('BC622', models.CharField(max_length=10)),
                ('BC622B', models.CharField(max_length=10)),
                ('BC623', models.CharField(max_length=10)),
                ('BC623B', models.CharField(max_length=10)),
            ],
        ),
    ]
