# Generated by Django 3.0.2 on 2020-01-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0002_runs_planned_depart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='trailer_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
