# Generated by Django 3.0.2 on 2020-01-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0002_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='Truck',
            field=models.CharField(max_length=50),
        ),
    ]
