# Generated by Django 3.0.2 on 2020-01-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0002_auto_20200130_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btrailer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='front_trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftrailer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=6)),
            ],
        ),
    ]
