# Generated by Django 3.0.2 on 2020-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0003_auto_20200127_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='depart_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='trailer_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
