# Generated by Django 3.0.2 on 2020-02-05 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0004_auto_20200131_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='planning_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runs',
            name='truck',
            field=models.CharField(choices=[('BEVS BEAUTY', 'BEVS BEAUTY'), ('BORN TO RUN', 'BORN TO RUN'), ('BROTHERS IN ARMS', 'BROTHERS IN ARMS'), ('CHARLOTTES WEB', 'CHARLOTTES WEB'), ('CLUDEN GREEN', 'CLUDEN GREEN'), ('COASTAL TRADER', 'COASTAL TRADER'), ('DANCING IN THE DARK', 'DANCING IN THE DARK'), ('DEWEY LOUIE', 'DEWEY LOUIE'), ('FIFTY SHADES', 'FIFTY SHADES'), ('GREEN ADDICTION', 'GREEN ADDICTION'), ('GREEN BARON', 'GREEN BARON'), ('GREEN CURRY', 'GREEN CURRY'), ('GREEN DREAM', 'GREEN DREAM'), ('GREEN EGGS', 'GREEN EGGS'), ('GREEN ENVY', 'GREEN ENVY'), ('GREEN GOBLIN', 'GREEN GOBLIN'), ('GREEN GODDESS', 'GREEN GODDESS'), ('GREEN GROCER', 'GREEN GROCER'), ('GREEN IVY', 'GREEN IVY'), ('GREEN LANTERN', 'GREEN LANTERN'), ('GREEN MAISE', 'GREEN MAISE'), ('GREEN MILE', 'GREEN MILE'), ('GREEN MILKY', 'GREEN MILKY'), ('GREEN MIST', 'GREEN MIST'), ('GREEN STRALLIS', 'GREEN STRALLIS'), ('GREEN TRUMP', 'GREEN TRUMP'), ('HARD ANTLER', 'HARD ANTLER'), ('HOT LOUIE', 'HOT LOUIE'), ('ICE LOUIE', 'ICE LOUIE'), ('JELLEY BABY', 'JELLEY BABY'), ('KING LOUIE', 'KING LOUIE'), ('LOYAL', 'LOYAL'), ('PASTA LOUIE', 'PASTA LOUIE'), ('STAR ATTRACTION', 'STAR ATTRACTION'), ('STAR LOUIE', 'STAR LOUIE'), ('THE DRIFTER', 'THE DRIFTER'), ('THE GUV', 'THE GUV'), ('THUNDER ROAD', 'THUNDER ROAD'), ('Z LAST', 'Z LAST'), ('TBC', 'TBC')], max_length=50),
        ),
    ]
