# Generated by Django 3.0.2 on 2020-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0004_auto_20200127_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='depart_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
