# Generated by Django 3.0.3 on 2020-02-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0005_auto_20200205_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='foodstuffs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='runs',
            name='gib',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4),
        ),
    ]
