# Generated by Django 3.0.3 on 2020-02-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0006_auto_20200225_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='run_details',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
