# Generated by Django 3.0.3 on 2020-02-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0007_runs_run_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='BC510',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
