# Generated by Django 3.0.3 on 2020-02-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0008_permit_bc510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='BC510',
        ),
    ]
