# Generated by Django 3.0.3 on 2020-02-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0009_remove_permit_bc510'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='cubic',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='runs',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
