# Generated by Django 3.0.3 on 2020-02-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0010_auto_20200226_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='Spare10',
        ),
    ]
