# Generated by Django 3.0.3 on 2020-02-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0011_remove_permit_spare10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='Spare1',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare2',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare3',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare4',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare5',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare6',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare7',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare8',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Spare9',
        ),
    ]
