# Generated by Django 3.0.3 on 2020-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0014_auto_20200226_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='A125',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='A125B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ASJ583',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='AZP219',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='B373J',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC503',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC503B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC506',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC506B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC507',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC507B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC509',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC509B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC510B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC511',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC511B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC513B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC514B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC516',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC516B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC518',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC518B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC519B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC520B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC601',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC601B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF001',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF002',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF002B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF004',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF005',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF005B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC401',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC402',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC403',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC404',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC408',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FC409',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='runs',
            name='truck',
            field=models.CharField(max_length=50),
        ),
    ]
