# Generated by Django 3.1b1 on 2020-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0018_auto_20200629_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='BC508',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BC508B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='BCF003',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='CS403',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='DJC531',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='DYS67',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='EWM744',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FD401',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FD402',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='FUM497',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='GMU582',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='GQS618',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='M339B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='M928M',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='MT4028',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='N771A',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='N8017',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='NI4214',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='Ole_Blue',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='Ole_Yellow',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='P839B',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='Q602A_Rear',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='R705S',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='RH3415',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='S2631',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='S2632',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SC301',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SC402',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SC403',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SK303',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SK304',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SK306',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SK401',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SK402',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SR401',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ST50_Front',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ST50_REAR',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ST61_Rear',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ST72_Rear',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SW301',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SW302',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SW304',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='SW401',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='U2982',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='W469D',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='permit',
            name='ZK7820',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='permit',
            name='BC603',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='runs',
            name='driver',
            field=models.CharField(blank=True, choices=[('Aaron Boys', 'Aaron Boys'), ('Aarron Robinson', 'Aarron Robinson'), ('Abhay Dhoundiyal', 'Abhay Dhoundiyal'), ('Adam Bright', 'Adam Bright'), ('Allan Barnden', 'Allan Barnden'), ('Allan Haua', 'Allan Haua'), ('Allan Woodfield', 'Allan Woodfield'), ('Amanda Brown', 'Amanda Brown'), ('Andrew Donehue', 'Andrew Donehue'), ('Andrew Shaw', 'Andrew Shaw'), ('Andrew Swaney', 'Andrew Swaney'), ('Antoine Aulnette', 'Antoine Aulnette'), ('Apera Deer', 'Apera Deer'), ('Asha Thomson-Lowes - RDNZ', 'Asha Thomson-Lowes - RDNZ'), ('Ashley Millard', 'Ashley Millard'), ('Austin Aitcheson', 'Austin Aitcheson'), ('Barry Milne', 'Barry Milne'), ('Blair Murphy', 'Blair Murphy'), ('Brian Greer', 'Brian Greer'), ('Brian Kenworthy', 'Brian Kenworthy'), ('Bronson Burgess', 'Bronson Burgess'), ('Bruce McLean', 'Bruce McLean'), ('C.Drew', 'C.Drew'), ('Cam Sleeman', 'Cam Sleeman'), ('Carl Laffey', 'Carl Laffey'), ('Carol Jasperse - TEMP', 'Carol Jasperse - TEMP'), ('Charmaine Proudman', 'Charmaine Proudman'), ('Chathura Don', 'Chathura Don'), ('Chontelle Brown', 'Chontelle Brown'), ('Chris Erskine', 'Chris Erskine'), ('Chris Hibbs', 'Chris Hibbs'), ('Christopher Bell', 'Christopher Bell'), ('Clive Riley', 'Clive Riley'), ('Coltin Manson', 'Coltin Manson'), ('Conrad Herbert', 'Conrad Herbert'), ('Craig Hewlett', 'Craig Hewlett'), ('Craig Miller - RDNZ', 'Craig Miller - RDNZ'), ('Daniel Chalmers', 'Daniel Chalmers'), ('Daniel Miller', 'Daniel Miller'), ('Daniel Munro', 'Daniel Munro'), ('Daniel Rodgers', 'Daniel Rodgers'), ('Darrell Clark', 'Darrell Clark'), ('Darryl Harvey', 'Darryl Harvey'), ('David Cross', 'David Cross'), ('David Dunn', 'David Dunn'), ('David Young', 'David Young'), ('Deane Rodgers', 'Deane Rodgers'), ('Dennis Brennan', 'Dennis Brennan'), ('Dion Dunlop', 'Dion Dunlop'), ('Duncan McCorkindale', 'Duncan McCorkindale'), ('Emma Southby', 'Emma Southby'), ('Felix Donnelly', 'Felix Donnelly'), ('G.Lowe', 'G.Lowe'), ('Gary Barnfather', 'Gary Barnfather'), ('Gary Kenton', 'Gary Kenton'), ('Gautam Prasad', 'Gautam Prasad'), ('Gavin Gilling', 'Gavin Gilling'), ('Geoffrey Harper', 'Geoffrey Harper'), ('Glen Clarkson', 'Glen Clarkson'), ('Glen Redmond', 'Glen Redmond'), ('Glenn Reeves', 'Glenn Reeves'), ('Graeme Yianakis', 'Graeme Yianakis'), ('Grant Lowe', 'Grant Lowe'), ('Grant Robertson', 'Grant Robertson'), ('Greg Carter', 'Greg Carter'), ('Greg Hunt', 'Greg Hunt'), ('Gurri Brar', 'Gurri Brar'), ('Hina Hunt', 'Hina Hunt'), ('Ian Tamepo', 'Ian Tamepo'), ('James Eggers', 'James Eggers'), ('Jamie Landreth', 'Jamie Landreth'), ('Jamie Wessels', 'Jamie Wessels'), ('Jan Kurak', 'Jan Kurak'), ('Jarred Matheson', 'Jarred Matheson'), ('Jay OBrien', 'Jay OBrien'), ('Jayden Manning', 'Jayden Manning'), ('Jeff Gardiner', 'Jeff Gardiner'), ('Jessie Wrigley', 'Jessie Wrigley'), ('Joe Garrett', 'Joe Garrett'), ('Joe Maehe', 'Joe Maehe'), ('John Boulton', 'John Boulton'), ('John Dodson-Cook', 'John Dodson-Cook'), ('John Lindsay', 'John Lindsay'), ('John Pringle', 'John Pringle'), ('John Sayer', 'John Sayer'), ('Karla Irvine', 'Karla Irvine'), ('Ken Owen', 'Ken Owen'), ('Kerry Evans', 'Kerry Evans'), ('Kevin Ludemann', 'Kevin Ludemann'), ('Kevin Murphy', 'Kevin Murphy'), ('Kurt Scoringe', 'Kurt Scoringe'), ('Kym Parsons', 'Kym Parsons'), ('Leigh Rout', 'Leigh Rout'), ('Leon Cooze', 'Leon Cooze'), ('Les Brooks', 'Les Brooks'), ('Leslie Mortimer', 'Leslie Mortimer'), ('Leslie Pennal', 'Leslie Pennal'), ('Liam Forsythe', 'Liam Forsythe'), ('Lyndon Buchanan', 'Lyndon Buchanan'), ('Mac McCall', 'Mac McCall'), ('Mangi Singh', 'Mangi Singh'), ('Matthew Best - AWF Nelson', 'Matthew Best - AWF Nelson'), ('Matthew Doherty', 'Matthew Doherty'), ('Michael Cotton', 'Michael Cotton'), ('Michael Currie', 'Michael Currie'), ('Michael Hector', 'Michael Hector'), ('Michael Scobie', 'Michael Scobie'), ('Michael Ward - RDNZ', 'Michael Ward - RDNZ'), ('Michael Warman', 'Michael Warman'), ('Michael Williams', 'Michael Williams'), ('Michelle Young', 'Michelle Young'), ('Mike Dennison', 'Mike Dennison'), ('Mitchell Wheeler', 'Mitchell Wheeler'), ('Monique Carthal', 'Monique Carthal'), ('Morgan Perry', 'Morgan Perry'), ('Murray Miller', 'Murray Miller'), ('Neil Bridson', 'Neil Bridson'), ('Neil Tompson', 'Neil Tompson'), ('Neville Browning', 'Neville Browning'), ('Nicolas Blacker - RDNZ', 'Nicolas Blacker - RDNZ'), ('Norman Ranford', 'Norman Ranford'), ('Oliver Victor-Dowling', 'Oliver Victor-Dowling'), ('Pare Pewhairangi', 'Pare Pewhairangi'), ('Paul Taiatini', 'Paul Taiatini'), ('Paul Tobin', 'Paul Tobin'), ('Peter Donald', 'Peter Donald'), ('Peter Martin', 'Peter Martin'), ('Peter McGowan', 'Peter McGowan'), ('Peter OSullivan', 'Peter OSullivan'), ('Peter Stringer', 'Peter Stringer'), ('Phil Whitcombe - RDNZ', 'Phil Whitcombe - RDNZ'), ('Philip Radford - RDNZ', 'Philip Radford - RDNZ'), ('Phillip Askin', 'Phillip Askin'), ('Ravi Sharma', 'Ravi Sharma'), ('Ray Johnson', 'Ray Johnson'), ('Regan Bertie', 'Regan Bertie'), ('Reve Bryce', 'Reve Bryce'), ('Rex Sharp', 'Rex Sharp'), ('Ricky Rodgers', 'Ricky Rodgers'), ('Riki Gilchrist', 'Riki Gilchrist'), ('Robert Beck', 'Robert Beck'), ('Robert Dee', 'Robert Dee'), ('Robert Eady', 'Robert Eady'), ('Robert Foote', 'Robert Foote'), ('Robert Keen', 'Robert Keen'), ('Robin Given', 'Robin Given'), ('Ronald Matthews', 'Ronald Matthews'), ('Ross Ward - RDNZ', 'Ross Ward - RDNZ'), ('Russell Harris', 'Russell Harris'), ('Russell Webb', 'Russell Webb'), ('Sachin Kapoor', 'Sachin Kapoor'), ('Sam Dampier-Crossley - RDNZ', 'Sam Dampier-Crossley - RDNZ'), ('Scott Edwards', 'Scott Edwards'), ('Sergey Antonov', 'Sergey Antonov'), ('Shaun Kincaid', 'Shaun Kincaid'), ('Shaun Mcgrath', 'Shaun Mcgrath'), ('Shaun Mills', 'Shaun Mills'), ('Sheik Ali', 'Sheik Ali'), ('Smilie Millard', 'Smilie Millard'), ('Stephen Arends', 'Stephen Arends'), ('Stephen Nelson', 'Stephen Nelson'), ('Stephen Wood', 'Stephen Wood'), ('Steve Day-Clarke', 'Steve Day-Clarke'), ('Steven Arps', 'Steven Arps'), ('Steven Kellow', 'Steven Kellow'), ('Steven Mcara', 'Steven Mcara'), ('Sunil Bhinchar', 'Sunil Bhinchar'), ('T.User', 'T.User'), ('Terry Duthie', 'Terry Duthie'), ('Terry Lewis', 'Terry Lewis'), ('Terry Markham', 'Terry Markham'), ('Tony Pupich', 'Tony Pupich'), ('Trevor Kelliher', 'Trevor Kelliher'), ('Troy Wilson', 'Troy Wilson'), ('Wayne Court', 'Wayne Court'), ('Wayne Kerr', 'Wayne Kerr'), ('Wayne Redmond', 'Wayne Redmond'), ('Winston Huhu', 'Winston Huhu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='truck',
            field=models.CharField(max_length=50),
        ),
    ]
