# Generated by Django 3.1b1 on 2020-08-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Runs', '0020_auto_20200630_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back_trailer',
            name='btrailer',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='front_trailer',
            name='ftrailer',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='runs',
            name='trailer_1',
            field=models.CharField(choices=[('A125', 'A125'), ('A125B', 'A125B'), ('ASJ583', 'ASJ583'), ('AZP219', 'AZP219'), ('B373J', 'B373J'), ('BC503', 'BC503'), ('BC506', 'BC506'), ('BC507', 'BC507'), ('BC508', 'BC508'), ('BC508B', 'BC508B'), ('BC509', 'BC509'), ('BC510', 'BC510'), ('BC511', 'BC511'), ('BC516', 'BC516'), ('BC518', 'BC518'), ('BC601', 'BC601'), ('BC602', 'BC602'), ('BC603', 'BC603'), ('BC603', 'BC603'), ('BC604', 'BC604'), ('BC605', 'BC605'), ('BC606', 'BC606'), ('BC607', 'BC607'), ('BC608', 'BC608'), ('BC609', 'BC609'), ('BC610', 'BC610'), ('BC614', 'BC614'), ('BC615', 'BC615'), ('BC619', 'BC619'), ('BC620', 'BC620'), ('BC621', 'BC621'), ('BC622', 'BC622'), ('BC623', 'BC623'), ('BCF001', 'BCF001'), ('BCF002', 'BCF002'), ('BCF003', 'BCF003'), ('BCF004', 'BCF004'), ('BCF005', 'BCF005'), ('DJC531', 'DJC531'), ('DYS67', 'DYS67'), ('EWM744', 'EWM744'), ('FC401', 'FC401'), ('FC402', 'FC402'), ('FC403', 'FC403'), ('FC404', 'FC404'), ('FC408', 'FC408'), ('FC409', 'FC409'), ('FC503', 'FC503'), ('FC504', 'FC504'), ('FC505', 'FC505'), ('FD401', 'FD401'), ('FD402', 'FD402'), ('FUM497', 'FUM497'), ('GMU582', 'GMU582'), ('GQS618', 'GQS618'), ('H180J', 'H180J'), ('M339B', 'M339B'), ('M441R', 'M441R'), ('M928M', 'M928M'), ('MT4028', 'MT4028'), ('N771A', 'N771A'), ('N8017', 'N8017'), ('NFC502', 'NFC502'), ('NI4214', 'NI4214'), ('P839B', 'P839B'), ('Q738U', 'Q738U'), ('R705S', 'R705S'), ('RH3415', 'RH3415'), ('S2631', 'S2631'), ('S2632', 'S2632'), ('SC301', 'SC301'), ('SC402', 'SC402'), ('SC403', 'SC403'), ('SK303', 'SK303'), ('SK304', 'SK304'), ('SK306', 'SK306'), ('SK401', 'SK401'), ('SK402', 'SK402'), ('SR401', 'SR401'), ('SW301', 'SW301'), ('SW302', 'SW302'), ('SW304', 'SW304'), ('SW401', 'SW401'), ('TBC', 'TBC'), ('U2982', 'U2982'), ('W469D', 'W469D'), ('ZK7820', 'ZK7820')], max_length=50),
        ),
        migrations.AlterField(
            model_name='runs',
            name='trailer_2',
            field=models.CharField(blank=True, choices=[('5Y411', '5Y411'), ('A125B', 'A125B'), ('BC503B', 'BC503B'), ('BC506B', 'BC506B'), ('BC507B', 'BC507B'), ('BC509B', 'BC509B'), ('BC510B', 'BC510B'), ('BC511B', 'BC511B'), ('BC513B', 'BC513B'), ('BC514B', 'BC514B'), ('BC516B', 'BC516B'), ('BC518B', 'BC518B'), ('BC519B', 'BC519B'), ('BC520B', 'BC520B'), ('BC601B', 'BC601B'), ('BC602B', 'BC602B'), ('BC603B', 'BC603B'), ('BC604B', 'BC604B'), ('BC605B', 'BC605B'), ('BC606B', 'BC606B'), ('BC607B', 'BC607B'), ('BC608B', 'BC608B'), ('BC609B', 'BC609B'), ('BC610B', 'BC610B'), ('BC614B', 'BC614B'), ('BC615B', 'BC615B'), ('BC619B', 'BC619B'), ('BC620B', 'BC620B'), ('BC621B', 'BC621B'), ('BC622B', 'BC622B'), ('BC623B', 'BC623B'), ('BCF002', 'BCF002'), ('BCF005', 'BCF005'), ('Blue', 'Blue'), ('FC501', 'FC501'), ('Q602A', 'Q602A'), ('ST27_R', 'ST27_R'), ('ST61_R', 'ST61_R'), ('Yellow', 'Yellow')], max_length=50, null=True),
        ),
    ]
